"""T5 - Ahmed body, 25 degree slant, half model (spec 13). Heavy,
CF_HEAVY_NP ranks (default 10, D-031).

Geometry from cases/T5_ahmed/geometry/make_ahmed.py (generated by the
Allrun if missing, with this interpreter: CF_PYTHON). Mesh: snappyHexMesh,
target 5-8 M cells (Allrun -mesh fine); CF_T5_MESH=coarse selects the ~1-2 M
development mesh instead (recorded in the result; spec runs use fine).

Pass, averaged force criterion for the oscillating wake (D-042 and its
addendum, user decisions; see test_T4_motorBike.py): both solvers have a
stationary window mean of Cd and Cl (harness function
bench/run_bench.py:stationary_mean, one window W for both solvers,
run_bench.CASES["T5"]["statWindow"] = 400 (D-068), capped at n, drift
<= max(1 %, 0.005)); window means within max(2 %, 0.002) (Cd) and
max(2 %, 0.01) (Cl) of simpleFoam on the same mesh; mean-field deltas
(coupledFieldCompare) with volume RMS |dUMean|/U_inf and |dpMean|/p_ref
<= 0.02 (proposed); time to convergence from the first stationary
window; static set <= 1 % of cells; nRollbacks == 0; peak RSS, wall
and CPU-hours recorded for both solvers. Informational only: both Cd within
+-10 % of the experimental 0.285 (Ahmed et al. 1984); y+ on the body.

The mesh is built once into run/T5_mesh (run/T5_mesh_coarse) and reused;
see the helpers in test_T4_motorBike.py.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pytest

from cflib import case as cfcase
from cflib import results

from test_T4_motorBike import (NP, assert_checks, budget_sets, compare,
                               fail_if_failed, mean_field_comparison,
                               mesh_dir, reference, run_solver,
                               speedup_record)

TEMPLATE = "T5_ahmed"
CD_EXP = 0.285
TOL_EXP = 0.10

sys.path.insert(0, str(cfcase.REPO / "bench"))
import run_bench  # noqa: E402

BUDGET = run_bench.CASES["T5"]["iters"]


def ahmed_env() -> dict:
    """The generator needs numpy-stl: run it with this interpreter."""
    return {"CF_PYTHON": sys.executable}


def yplus_body(case: Path) -> dict | None:
    """min/max/average y+ on the body patches at the last write
    (postProcessing/yPlus/<start>/yPlus.dat, per-patch rows)."""
    base = case / "postProcessing" / "yPlus"
    if not base.is_dir():
        return None
    rows = []
    for f in sorted(base.glob("*/yPlus.dat")):
        for line in f.read_text().splitlines():
            if line.startswith("#") or not line.strip():
                continue
            tok = line.split()
            if len(tok) >= 5 and tok[1].startswith("ahmed"):
                try:
                    rows.append((float(tok[0]), tok[1], float(tok[2]),
                                 float(tok[3]), float(tok[4])))
                except ValueError:
                    pass
    if not rows:
        return None
    last = max(r[0] for r in rows)
    sel = [r for r in rows if r[0] == last]
    return {"time": last, "patches": [r[1] for r in sel],
            "min": min(r[2] for r in sel), "max": max(r[3] for r in sel),
            "average": sum(r[4] for r in sel) / len(sel)}


@pytest.mark.heavy
def test_T5(foam):
    variant = os.environ.get("CF_T5_MESH", "fine")
    mesh_args = ["-mesh", variant]
    mesh_name = "T5_mesh" if variant == "fine" else f"T5_mesh_{variant}"
    env = ahmed_env()
    mesh = mesh_dir(TEMPLATE, mesh_name, mesh_args, NP, extra_env=env)

    # run names shared with the report (run_bench.t5_run_name): T5_np10 on
    # the fine mesh, T5_coarse_np10 on the coarse one
    name = run_bench.t5_run_name(NP, variant)
    # wake case: averaged force criterion (D-042)
    osc = run_bench.is_oscillatory("T5")
    ref_case, ref = reference(
        TEMPLATE, mesh, f"ref_{name}", mesh_args,
        budget_sets("simpleFoam", BUDGET["simpleFoam"]), oscillatory=osc,
        case_name="T5")

    case, rec = run_solver(
        TEMPLATE, mesh, name, "coupledFoam", mesh_args,
        budget_sets("coupledFoam", BUDGET["coupledFoam"]), extra_env=env,
        oscillatory=osc, case_name="T5")
    fail_if_failed(name, rec, {"case": "T5", "meshVariant": variant,
                               "reference": ref})

    # mean-field delta comparison (D-042 addendum), as in T4
    field = (mean_field_comparison(case, rec, ref_case, ref, "T5")
             if osc else None)
    cmp = compare(rec, ref, oscillatory=osc, field=field)
    stats_file = mesh / "geometry" / "ahmed25_stats.json"
    meshing = mesh / "meshing.json"
    info = {
        "case": "T5", "meshVariant": variant, "meshDir": str(mesh),
        "meshing": json.loads(meshing.read_text()) if meshing.exists() else None,
        "geometry": json.loads(stats_file.read_text())
        if stats_file.exists() else None,
        "CdExp": CD_EXP, "tolExp": TOL_EXP,
        "yPlusBody": yplus_body(case),
        "yPlusBodyRef": yplus_body(ref_case),
        "reference": ref,
    }
    # Informational: experiment (Ahmed et al. 1984), not a pass criterion
    for key, r in (("CdExpRelDiff", rec), ("CdExpRelDiffRef", ref)):
        if r.get("Cd") is not None:
            info[key] = abs(r["Cd"] - CD_EXP) / CD_EXP
    info["withinExp"] = (info.get("CdExpRelDiff") is not None
                         and info.get("CdExpRelDiffRef") is not None
                         and info["CdExpRelDiff"] <= TOL_EXP
                         and info["CdExpRelDiffRef"] <= TOL_EXP)
    rec.update(cmp)
    rec.update(speedup_record(ref_case, ref))
    rec.update(info)
    results.write("tests", name, rec)
    assert_checks(cmp, rec, ref)
